name: AdvancedCombat
author: AEDXDEV
main: AEDXDEV\Combat\Main
api: 5.0.0
version: 3.0.0
description: This plugin prevents players from escaping during combat and allows you to check if a player is currently engaged in combat.
permissions:
  combatsettings.cmd:
    default: true